### PR TITLE
Fixed compatibility issue with SYCL-1.2.1

### PR DESCRIPTION
**Pull request by tianshilei1992**
Current implementation is not compatible with latest SYCL-1.2.1. This patch is to make it work.

### CODE REVIEW

**Comment by tomdeakin** [comment]
@Ruyk, does this update look consistent with what is supported by the ComputeCpp compiler? I believe that supports SYCL 1.2.1 now.

**Comment by tianshilei1992** [comment]
@tomdeakin ComputeCpp claims that they're fully SYCL 1.2.1 compatible. :)

**Comment by GeorgeWeb** [comment]
Hello,

I am aware that I made a PR which is a duplicate of this one without realizing that this one exists in the first place when I went and pushed mine.

**However**, I have given a complete explanation on why are the changes needed at this stage, putting some light on this **non-conformant (yet)** functionality that is however supported by **ComputeCpp**.

I suggest going over it before deciding how to proceed: **[PR Link](https://github.com/UoB-HPC/BabelStream/pull/58).**

Regards,

Georgi

**Comment by Ruyk** [comment]
The parallel_for overload that takes a kernel as a first argument was in SYCL 1.2 but somehow we missed it on the 1.2.1 spec. In my opinion it was just an oversight, we've raised this internally in the Khronos group.

**Comment by tomdeakin** [comment]
Fixed by #58.

**Pull request closed without merging**
