### PR TITLE
added OpenCL for the ROCm platform

### PR DESCRIPTION
**Pull request by psteinb**
```
GPU-STREAM
Version: 3.1
Implementation: OpenCL
Running kernels 100 times
Precision: double
Array size: 268.4 MB (=0.3 GB)
Total size: 805.3 MB (=0.8 GB)
Using OpenCL device gfx803
Driver: 1.1 (HSA,LC)
Reduction kernel config: 256 groups of size 256
Function    MBytes/sec  Min (sec)   Max         Average     
Copy        409471.915  0.00131     0.00137     0.00133     
Mul         409624.689  0.00131     0.00137     0.00134     
Add         418105.745  0.00193     0.00219     0.00200     
Triad       417470.030  0.00193     0.00228     0.00199     
Dot         461460.829  0.00116     0.00126     0.00120
```
created a specific target for OpenCL on the rocm platform. The only difference to vanilla gcc are the CXXFLAGS. But consider this as a placeholder for future rocm releases when hcc can be used to link OpenCL binaries as well.

### CODE REVIEW

**Comment by Ruyk** [comment]
Which hardware is gfx803 ?

**Comment by psteinb** [comment]
that is a R9 Fiji Nano with 4GB of HBM1.

**Comment by jrprice** [comment]
I'm not sure I understand the need for this change. The host compiler being used is still GNU not HCC, so the only actual difference is the addition of a non-standard include path. This seems like it could just be achieved with `make -f OpenCL.make COMPILER=GNU EXTRA_FLAGS="-I/opt/rocm/opencl/include"`, rather than adding a specific configuration for it.

**Comment by psteinb** [comment]
true, but this way it's more integrated. feel free to merge or close the PR if you think this is not needed.

**Pull request closed without merging**
